- name: disable nodejs 
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs:20 
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs 
  ansible.builtin.package:
    name: nodejs 
    state: present 

- name: creating app directory 
  ansible.builtin.file:
    path: /app 
    state: directory 

- name: creating roboshop user 
  ansible.builtin.user:
    name: roboshop 
    system: yes 
    shell: /sbin/nologin
    home: /app 

- name: downloading user code 
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
    dest: /tmp/user.zip

- name: extracting user code 
  ansible.builtin.unarchive:
    src: /tmp/user.zip
    dest: /app 
    remote_src: yes 

- name: installing nodejs dependencies 
  community.general.npm: 
    path: /app 

- name: copy user.service file 
  ansible.builtin.copy:
    src: user.service 
    dest: /etc/systemd/system/user.service

- name: reload user 
  ansible.builtin.systemd_service:
    daemon_reload: true 

- name: start and enable user 
  ansible.builtin.service:
    name: user 
    state: started 
    enabled: yes