- name: installing mysql server 
  ansible.builtin.package:
    name: mysql-server
    state: present 

- name: start and enable mysqld 
  ansible.builtin.service:
    name: mysqld 
    state: started
    enabled: yes 

- name: changing default root password 
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
