- name: app setup 
  include_role:
    name: common 
    tasks_from: app-setup 

- name: nodejs setup
  include_role:
    name: common 
    tasks_from: nodejs

- name: systemd setup 
  include_role:
    name: common 
    tasks_from: systemmd_setup 

- name: copying mongo.repo 
  ansible.builtin.copy:
    src: mongo.repo 
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client 
  ansible.builtin.package:
    name: mongodb-mongosh
    state: installed 

- name: loading master data 
  ansible.builtin.shell: mongosh --host mongodb.cloudwithmanoj.online </app/db/master-data.js