- name: create app directory 
  ansible.builtin.file:
    path: /app 
    state: directory 

- name: create roboshop system user 
  ansible.builtin.user:
    name: roboshop 
    system: yes 
    shell: /sbin/nologin
    home: /app 

- name: downloading catalogue code 
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: extracting catalogue code 
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app 
    remote_src: yes