- name: copying catalogue.service file 
  ansible.builtin.copy:
    src: catalogue.service 
    dest: /etc/systemd/system/catalogue.service

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true 

- name: start and enable catalogue 
  ansible.builtin.service:
    name: catalogue 
    state: started 
    enabled: yes 